# Generated by Django 2.2.1 on 2019-05-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('language', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=16)),
                ('genre', models.CharField(choices=[('horror', 'Horror'), ('comedy', 'Comedy'), ('action', 'Action'), ('drama', 'Drama')], max_length=10)),
                ('rating', models.IntegerField(default=0, help_text='values between 0 to 10')),
            ],
        ),
    ]
